### ISSUE TITLE
Excavator doesn't break mod-added stone types

### ISSUE THREAD

**Issue by Murdermancer** [DancZer/Excavator#1]
Love the mod! Just downloaded the new 1.7.1 version, and it doesn't seem to break mod-added stone types - I've got Create installed, which seems to add a lot of Limestone and Scoria, but the Excavator just stops in front of these. If you manually break them, it continues on until it encounters more, and then stops once more.

**Comment by DancZer** [comment]
Hi!

Thank you for the issue. I will fix it for the next release.

**Comment by DancZer** [comment]
Should be fixed in the Release 1.7.2 
c205b85
