### ISSUE TITLE
No block drops

### ISSUE THREAD

**Issue by SylisMC** [DancZer/Excavator#10]
Fabric load 0.15.1
Fabric API v0.77.0+1.19.2
Excavator v2.0.1

The Excavator breaks blocks but they don't get put into the cart and they don't drop on the ground. they just get removed from the game

**Comment by maiguel5** [comment]
same, tried 2.0.1 and 2.0.0, tried in a new instance with 0 extra mods, the behavior is excavator breaking blocks but 0 drops, no sense.

**Comment by DancZer** [comment]
Thank you for the feedback! I will investigate it next week. 
Does this happen with every majority of the blocks? Gravel, stone etc?
Can you provide any log file or a save? Thanks in advance!

**Comment by DancZer** [comment]
> same, tried 2.0.1 and 2.0.0, tried in a new instance with 0 extra mods, the behavior is excavator breaking blocks but 0 drops, no sense.

Thank you for the feedback! I will investigate it next week.
Does this happen with every majority of the blocks? Gravel, stone etc?
Can you provide any log file or a save? Thanks in advance!

**Comment by maiguel5** [comment]
[latest.log](https://github.com/DancZer/Excavator/files/13997466/latest.log)
Does this ... etc?
YES
Can you ... advance!
YES

Oh, and tested with dedicated server too, same behavior.

How to:
1. New instance in curseforge launcher.
2. Put together:
- minecraft 1.19.2
- java 17
- fabricloader 0.14.24
- fabric-api 0.77.0+1.19.2
- excavator 2.0.1-Fabric (or your preffered version :D)
3. Create a new world and give yourself a brand new excavator.
4. Push it to the rocks.

Expected (sadly) results:
- Blocks Break, and you can pick the blocks... if you are really close to them, but if u are behind the machine or far away... they will totally obliterate from existence forever.
- Machine won't save any block.
- Blocks somehow dissapear after complete the animation of breaking.


If i can help with something as user, make me know ^^ and if u finally solve it with a new version, of course, make me know too, i will love to test the full working version :D the excavator itself looks so nice to be fair.
