### ISSUE TITLE
Jade mod conflict

### ISSUE THREAD

**Issue by TheWopaMan** [DancZer/Excavator#2]
When using Jade mod and aiming excavator the game crash. Version 1.16.4.

**Comment by Snownee** [comment]
Hello I am developer of Jade. I think you should implement `IForgeEntityMinecart#getCartItem` since your minecart type is null. It may cause NPE.
https://github.com/Snownee/Jade/issues/23

**Comment by DancZer** [comment]
@Snownee Hi. Thank you for your support. If you have time and you want to fix it, you can create a PR. Otherwise I will try to fix it after work.

**Comment by DancZer** [comment]
Test needed.

**Comment by DancZer** [comment]
Fixed in release 1.8.2
