### ISSUE TITLE
Doesnt appear to be functioning as intended

### ISSUE THREAD

**Issue by SylisMC** [DancZer/Excavator#6]
fabric-api-0.68.0+1.19.2.jar
Excavator-2.0.0-Fabric.jar

Excavator thinks its met an obstacle as soon as you place it, and will not budge, it doesn't matter if you put materials in it or not

**Comment by DancZer** [comment]
@SylisMC Does it display any particle effects? (currently the particle effects shows the statuses of the excavator, this will be changed in the future).

**Comment by SylisMC** [comment]
Yes, the particle effects display as soon as the cart is placed.

**Comment by DancZer** [comment]
That's normal.

You have to place a track, pickaxe and shovel in it. Torch is optional.

The mining speed depends on the pickaxe and shovel type you put in.
