### ISSUE TITLE
The Excavator doesn't work

### ISSUE THREAD

**Issue by MCD4U** [DancZer/Excavator#8]
I've followed the instructions by putting torches, rail, and a tool in the excavator, and pushing it with a furnace minecart but the excavator doesn't do anything. It just stays in one place and doesn't move; you can't even push it. It is constantly showing the purple particles. I don't think this is because of mod conflicts because the issue still occurs after disabling the mods. I'm using fabric 1.19.2 and with the latest version of the mod.

**Comment by maiguel5** [comment]
You need both tools, pickaxe and shovel, not just one.
